name: Build Mahmoud Keyboard

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: تحميل المشروع
        uses: actions/checkout@v4

      - name: إعداد Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: تثبيت Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.6'

      - name: بناء تطبيق Android
        run: gradle assembleDebug

      - name: حفظ APK
        uses: actions/upload-artifact@v4
        with:
          name: Mahmoud-Keyboard-APK
          path: '**/build/outputs/apk/**/*.apk'
